### ISSUE TITLE
Course constraints: schedule, required courses and electives

### ISSUE THREAD

**Issue by floswald** [ScPo-CompEcon/CourseMatch.jl#11]
related to #4 

add matrices for each set of constraints (schedule, required courses and electives)

**Comment by mdesevricourt** [comment]
One way to implement the constraint of "classes should not be at the same time" is to have a feasibility matrix F, each row and column corresponding to a course, with 0s everywhere except when two classes clash with each other. Let x be the demand vector. Then, we could add to the optimizer the constraint that x'Fx = 0 

For example, if we have 3 courses and course 1 and course 2 cannot be taken together we would have. 

F = [0 1 0
       1 0 0
       0 0 0]

For x = [0 1 1] (feasible), we thus have x'Fx = 0
and for x = [1 1 0] (infeasible) we have x'Fx = 2

Do you think that could work in our algorithm?

**Comment by mdesevricourt** [comment]
I think constraints of the type "you have to take k courses from this list of n" (as for the electives) are even easier to deal with. 
Let's say you have 10 possibles courses. 5 of them are electives and the students have to be registered in exactly 3 of them. Then, supposing the electives are the first ones in the list, we could have a vector of requirements like this:
r = [1 1 1 1 1 0 0 0 0 0] and a constraint of the form: 
x' * r -5 = 0 with x the demand vector.

**Comment by Gegas2231** [comment]
I implemented this issue in a recent pull request on the demand function. 

The timetable clashes are implemented as described above, the matrix of feasible time schedules flags with 1 a clash, 0 otherwise.

I also considered program and semester restrictions, that is, the student can only have a demand on the courses on his/her program and corresponding semester. This does not mean that students will only be able to take courses in their own school or in contradiction with the electives available throughout the student years. Instead think of these matrices as flags, again, 1 if the course must NOT be taken for that student given her program or semester, say a public affairs L1 should not be able to take Macroeconomics 3 of the Economics' M2 program.

Now, regarding the mandatory and electives, my understanding is that mandatory courses must be taken, no room to choice, like micro, macro and metrics for our program as example. so this is a first restriction, the demand of this course should be 1 in each mandatory course. On the other hand, the electives work as described in the comment above, the constraint follows the procedure described, I only changed the sign for a >= instead of = since the number of electives is a minimum.

Please correct me if I am wrong in any of my thoughts or understanding of the course constraints.
